on:
    issues:
      types: [labeled]

name: "Publish issue as post"
jobs:
    publish-issue:
        if: github.event.label.name == 'action:publish'
        runs-on: ubuntu-latest
        env:
            POST_BODY: '${{ github.event.issue.body }}'
        steps:
            - uses: actions/checkout@v4
            - name: Create commits
              run: |
                export POST_DIRECTORY="$(date +"%Y")/$(date +"%m")/$(date +"%d")"
                mkdir -p $POST_DIRECTORY
                x=1
                cond=true
                time while $cond
                do
                    if [ ! -d $POST_DIRECTORY/$x ]; then
                        mkdir -p $POST_DIRECTORY/$x
                        export TARGET_DIRECTORY=$POST_DIRECTORY/$x
                        cond=false
                    fi
                    x=$(( $x + 1 ))
                done

                export POST_DATE=$(date +"%Y-%m-%d")
                export POST_TITLE="${{ github.event.issue.title }}"
                export FULL_PATH="$TARGET_DIRECTORY/post.txt"
                git config user.name 'Publish Bot'
                git config user.email 'publish-bot@github.com'
                
                export CURRENT_DATE=$(TZ=UTC date -v +1H +"%Y-%m-%d %T")
                POST_BODY=$(sed "s/date: '???'/date: '$CURRENT_DATE'/" <<< $POST_BODY)
                echo "$POST_BODY" >> $FULL_PATH

                git add $FULL_PATH

                git commit -m "Publish $POST_TITLE"

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                title: "New Post: ${{ github.event.issue.title }}"
                body: "Closes #${{ github.event.issue.number }}.\n\n This PR has been generated automatically."
            - uses: actions-ecosystem/action-remove-labels@v1
              with:
                labels: action:publish